spring:
  datasource:
    url: jdbc:mysql://localhost/friends?useSSL=false&serverTimezone=UTC
    username: tutorials
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true